class AuthenticationError(Exception):
    pass


class ResourceNotFoundError(Exception):
    pass
